### ISSUE TITLE
Double check that the executables were cross compiled in the release program

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-incubator/apiserver-builder-alpha#156]
run `file <file-name>` or a go-lib equivalent after completing cross compile and check the output to make sure they have the right architecture to prevent more regressions

**Comment by metmajer** [comment]
Just wondering if there's a go package that implements this functionality since `file` is not present across major Linux distros ootb.

**Comment by pwittrock** [comment]
@metmajer Good point

**Comment by damongant** [comment]
It does indeed:

https://golang.org/pkg/debug/elf/
https://golang.org/pkg/debug/pe/
