### ISSUE TITLE
Custom authentication layer on the custom api server

### ISSUE THREAD

**Issue by alok87** [kubernetes-incubator/apiserver-builder-alpha#198]
is it possible to build a custom api server authentication in the api server built from api server builder.
I want to authenticate the user using github and generate a token for him and authorize him for some actions.

**Comment by damongant** [comment]
Since you're never supposed to directly call the custom apiserver, all requests pass through the authentication layer (e.g. RBAC) you have set up on the kubernetes-apiserver, so you could set up role bindings there.
