### ISSUE TITLE
Document external dependency management

### ISSUE THREAD

**Issue by mattmoor** [kubernetes-incubator/apiserver-builder-alpha#200]
The generated code puts a `glide.yaml` in the root of the repo and clones the `apiserver-builder` `vendor/` directory, but `glide up` updates a lot of stuff and `apiserver-boot run in-cluster` stops working.

I'm trying to include some additional stuff to talk to Google services via `google-api-go-client`, but can't figure out the best way to pull that in without disturbing the nicely laid out base deps.

**Comment by mattmoor** [comment]
@pwittrock Any pointers?

**Comment by pwittrock** [comment]
@mattmoor I am OOO for the rest of the year.  Lets sync up in 2018

**Comment by pwittrock** [comment]
Try deleting glide, and adding a new one that ignores all the vendored stuff.

**Comment by mattmoor** [comment]
LOL ok, I thought we were meeting tomorrow? :)

**Comment by mattmoor** [comment]
IDK if it is possible to have it ignore other vendored stuff: https://github.com/Masterminds/glide/issues/579 :(

**Comment by mattmoor** [comment]
I was able to get it to build by fetching it onto my `GOPATH`.

This is an ok band-aid, but I'd still like to have a command to put `vendor/` into a good state.  LMK if you have any suggestions (given the above issue), but no rush.

Have a good holiday!

**Comment by mattmoor** [comment]
We moved [our starter fork](https://github.com/grantr/helloworld-crd) of `k8s.io/sample-controller` over to using `dep` and it works pretty well (even with Bazel).

@grantr did this for us, and IIUC it was mostly just `dep init` and `dep prune`.

For adding dependencies and whatnot, we added `./hack/update-deps.sh`.
