### ISSUE TITLE
RBAC enabled minikube cluster don't with addon apiserver

### ISSUE THREAD

**Issue by WIZARD-CXY** [kubernetes-incubator/apiserver-builder-alpha#205]
I followed the guide https://github.com/kubernetes-incubator/apiserver-builder/blob/master/docs/running_in_minikube.md to set things up. Only with I started minikube with `minikube start --extra-config=apiserver.Authorization.Mode=RBAC`
Then I can list pod but not list my self-defined resources,  the logs shows 

```
E1231 10:31:30.043187   25566 reflector.go:205] gitlab.alibaba-inc.com/sigma/sigma-k8s-apiserver/pkg/controller/sharedinformers/zz_generated.api.register.go:54: Failed to list *v1alpha1.Deployment: deployments.extensions.sigma is forbidden: User "system:anonymous" cannot list deployments.extensions.sigma at the cluster scope
```

I wonder why and how can I fix it, thanks in advance @pwittrock

**Comment by DirectXMan12** [comment]
Looks like something hasn't set up delegated auth checking correctly.  Looks like we pass `authentication-skip-lookup` when running with minikube, which means that our API server isn't going to check the central API server for authentication certs.  This was probably don't because minikube didn't/doesn't populate certificates correctly.  I haven't checked it in a while, but if it still doesn't, it needs to start soon.

**Comment by WIZARD-CXY** [comment]
>Looks like something hasn't set up delegated auth checking correctly. Looks like we pass authentication-skip-lookup when running with minikube, which means that our API server isn't going to check the central API server for authentication certs. This was probably don't because minikube didn't/doesn't populate certificates correctly. I haven't checked it in a while, but if it still doesn't, it needs to start soon.
Yeah, I agree. I removed the `authentication-skip-lookup` flag manually and it now works

**Comment by DirectXMan12** [comment]
@pwittrock we should drop that, assuming minikube sets things up correctly now (if they don't, we should get on their case to do that, because it's really inconvenient).

**Comment by WIZARD-CXY** [comment]
@pwittrock I just use minikube, I don't quite know about where controller-manager is running in minikube.The whole reproduce procedure is in the first message I sent in this issue.

**Comment by ichekrygin** [comment]
Hi, it looks like I am hitting the same issue:
```
E0226 23:30:59.997581   29007 reflector.go:205] github.com/bar/foo/pkg/controller/sharedinformers/zz_generated.api.register.go:54: Failed to list *v1alpha1.MyType: mytype.bar.foo.io
 is forbidden: User "system:anonymous" cannot list mytype.bar.foo.io at the cluster scope
```

```
minikube version: v0.25.0
minikube start --extra-config=apiserver.Authorization.Mode=RBAC --kubernetes-version=v1.9.0 
```

Initially, controller reports, which I assume is expected, until new `APIService` is registered
```
E0226 23:42:28.153690    3063 reflector.go:205] github.com/bar/foo/pkg/controller/sharedinformers/zz_generated.api.register.go:54: Failed to list *v1alpha1.MyType: the server could not find the requested
 resource (get mytype.bar.foo.io)
```

However, after 10-30 seconds (depending on `VBox` mood), `couldn not find` error is replaced by `is forbidden`, even though the new `APIServer` is returned by 
```
kubectl api-versions
```

Further attempts to provision the instance types are failing (expected) with:
```
 kubectl create -f sample/mytype.yaml
Error from server (Forbidden): error when creating "sample/mytype.yaml": mytype.bar.foo.io is forbidden: User "system:anonymous" cannot create mytype.bar.foo.io in the namespace "default"
```

@pwittrock, pls let me know if you need any assistance w/ repro.

**Comment by DirectXMan12** [comment]
@ichekrygin have you removed the `authentication-skip-lookup` flag?

**Comment by ichekrygin** [comment]
@DirectXMan12 No, I don't think so. To start apiserver and controller I ran (per docs):
```
apiserver-boot run local-minikube
```

**Comment by DirectXMan12** [comment]
you'll need to do that, then
