### ISSUE TITLE
Add-on apiserver doesn't have admission control plugin

### ISSUE THREAD

**Issue by WIZARD-CXY** [kubernetes-incubator/apiserver-builder-alpha#206]
I look through the code, looks like we don't have admission controllers like namespacelifecycle https://kubernetes.io/docs/admin/admission-controllers/#namespacelifecycle supported in add-on apiserver for now.
I wonder if it is possible to add it?

**Comment by WIZARD-CXY** [comment]
![admit nil](https://user-images.githubusercontent.com/2142864/34639412-e3a39b18-f31a-11e7-924f-db038d2bb0d9.png)
Now the admit is nil

**Comment by pires** [comment]
Admission-controller plugins, like many other things, are specific to `kube-apiserver`. That's where you should hook your customized plugins.

**Comment by yue9944882** [comment]
ref #266
