### ISSUE TITLE
[Question] How to use another database/custom storage to replace ETCD

### ISSUE THREAD

**Issue by klustria** [kubernetes-incubator/apiserver-builder-alpha#226]
Would like to get tips on how to implement using another database to replace ETCD.

**Comment by klustria** [comment]
According to this link: https://kubernetes.io/docs/concepts/api-extension/custom-resources/#should-i-add-a-custom-resource-to-my-kubernetes-cluster, you can use Custom Storage for aggregated API - " If you need storage with a different performance mode (for example, time-series database instead of key-value store) or isolation for security (for example, encryption secrets or different".

Would appreciate if somebody can provide tips on how to implement another database/custom storage with the api-server created by apiserver-builder.

**Comment by yue9944882** [comment]
hey @klustria, (if u were still hitting this issue) please re-post this to kubernetes/kubernetes repo.
