### ISSUE TITLE
Version for Kubernetes-1.10

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-incubator/apiserver-builder-alpha#241]
Hi,
Can you please release a version for Kubernetes-1.10 release? Also, is kubebuilder supposed to superseded this tool or kubebuilder is for CRDs and this one is for EAS-es?

Thanks.

**Comment by yue9944882** [comment]
hey @tamalsaha, are you still hitting this issue? release-1.10 we can provide a release-1.10 if that helps.

> Also, is kubebuilder supposed to superseded this tool or kubebuilder is for CRDs and this one is for EAS-es?

long-termly, i suppose it's a yes. while for now, CRDs have some pending underlying issues so.. the apiserver builder will move on

**Comment by Kashomon** [comment]
I would love this. I'm using this library and would love to upgrade to kube apimachinery 1.10 to pick up a bunch of advancements in CRDs, but I can't go all the way to 1.12 (which is what has happened on master).

**Comment by tamalsaha** [comment]
We are not planning to use this. Thanks for checking.
