### ISSUE TITLE
Kind name Plurals incorrectly handled 

### ISSUE THREAD

**Issue by devdattakulkarni** [kubernetes-incubator/apiserver-builder-alpha#243]
I created a Kind that ends with an 's' as follows:

apiserver-boot create group version resource --group groupname --version v1alpha1 --kind Postgres

Then tried to build executables:
apiserver-boot build executables

And got following error:
pkg/controller/sharedinformers/zz_generated.api.register.go:54:37: si.Factory.Groupname().V1alpha1().Postgres undefined (type "github.com/../../pkg/client/informers_generated/externalversions/groupname/v1alpha1".Interface has no field or method Postgres)
2018/05/25 15:32:07 exit status 2

The generated Interface definition in informers_generated/externalversions/groupname/v1alpha1 is as follows:

type Interface interface {
        // Postgreses returns a PostgresInformer.
        Postgreses() PostgresInformer
}

So this looks like issue with how plural names are handled internally. 

This might be similar to https://github.com/kubernetes-sigs/kubebuilder/issues/153

**Comment by shashidharatd** [comment]
I too faced this issue. Api object naming is very crucial and we had to opt for workaround and is not an ideal situation.

**Comment by damongant** [comment]
ref: https://github.com/kubernetes-incubator/apiserver-builder/blob/master/cmd/apiregister-gen/generators/controller_generator.go#L66
