### ISSUE TITLE
controller error - the server could not find the requested resource 

### ISSUE THREAD

**Issue by tkashem** [kubernetes-incubator/apiserver-builder-alpha#247]
After going through the steps outlined in `https://github.com/kubernetes-incubator/apiserver-builder/blob/master/docs/running_in_cluster.md` I am seeing the following errors from the controller instance. 

```
E0611 18:24:52.016992       1 reflector.go:205] github.com/tkashem/my-extension/pkg/controller/sharedinformers/zz_generated.api.register.go:54: Failed to list *v1alpha1.MyType: the server could not find the requested resource (get mytypes.batch.widget.com)
```

The apiserver and etcd instances seem to be up and running.
Output of `kubectl version` is shown below
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.1+a0ce1bc657", GitCommit:"a0ce1bc", GitTreeState:"clean", BuildDate:"2018-06-07T14:40:55Z", GoVersion:"go1.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1+a0ce1bc657", GitCommit:"a0ce1bc", GitTreeState:"clean", BuildDate:"2018-05-30T17:19:57Z", GoVersion:"go1.9", Compiler:"gc", Platform:"linux/amd64"}
```

`kubectl api-versions` does not list my extented type. I used the following commands to generate my type
```
apiserver-boot init repo --domain widget.com
apiserver-boot create group version resource --group batch --version v1alpha1 --kind MyType
```

My kubernetes cluster is from a minishift installation, dont think it should make any difference but wanted to mention it.
I am not conversed in k8s internals, so any pointers toward troubleshooting this would be really appreciated.

Version of `apiserver-boot` used is 
```
apiserver-boot version
Version: version.Version{ApiserverBuilderVersion:"v1.9-alpha.4", KubernetesVendor:"1.8.1", GitCommit:"8b47e32969f05f189515e1e7b351d5c82c149886", BuildDate:"2018-05-06-16:06:57", GoOs:"linux", GoArch:"amd64"}
```

Thanks in advance!

**Comment by damongant** [comment]
Check the output of `kubectl describe apiservice v1alpha.widget.com`, the status field should give you a hint.

**Comment by tkashem** [comment]
Thanks a lot, I was able to solve the issue. After running the above command the `status` field reflected the root cause. 
```
Status:
  Conditions:
    Last Transition Time:  2018-06-12T13:52:40Z
    Message:               no response from https://172.30.226.248:443: Get https://172.30.226.248:443: dial tcp 172.30.226.248:443: getsockopt: connection refused
    Reason:                FailedDiscoveryCheck
    Status:                False
    Type:                  Available
Events:                    <none>
```

I had made some changes to `config/apiserver.yaml` file to get the `apiserver` pod running - For example I had to change the default binding port from `443` to `--secure-port=6443` because `apiserver` container threw a 'permission denied - cannot bind to 443` error.

But I forgot to update the `targetPort` of `Service` definition. Once I made this fix it is working. Thanks again!
