### ISSUE TITLE
Subresources on 'existing' Kinds

### ISSUE THREAD

**Issue by devdattakulkarni** [kubernetes-incubator/apiserver-builder-alpha#248]
We had a requirement where we wanted to use custom subresources on existing Kinds such as Pods. An example of this is the custom metrics (https://github.com/kubernetes/metrics).

We tried to use apiserver-builder for our use-case but it did not work. It looks like with apiserver-builder we can create subresources only on a Custom Resource that is first created using apiserver-builder.

I was wondering if there is plan to support subresource generation without requiring resource creation first.

In the mean while, we solved our problem using sample-apiserver as the starting point and adding our custom subresource endpoints into it. Here are pointers to our solution if anyone comes here with requirements similar to ours:

1) Repository:
https://github.com/cloud-ark/kubeprovenance

2) Blog post explaining various options we tried:
https://medium.com/@cloudark/our-journey-in-building-a-kubernetes-aggregated-api-server-29a4f9c1de22

**Comment by DirectXMan12** [comment]
You basically need custom/hacked-up API installation logic to handle this (that's what we do in the custom-metrics-apiserver builder).  It's... non-trivial, and generally somewhat specific to the particular use case (do you want to work as an aggregated API server?  If so, how are you representing group-versions?  What subresources do you want available, and how are you exposing them?)
