### ISSUE TITLE
apiserver-boot must be run from the directory containing the go package to bootstrap.

### ISSUE THREAD

**Issue by mlushpenko** [kubernetes-incubator/apiserver-builder-alpha#251]
can't finish the installation, probably an easy fix, but I am not sure what to do here - untar vendor tar and copy apiserver-boot somewhere there?

```
/usr/local/apiserver-builder/bin  ls -l
total 214496
-r-xr-xr-x@ 1 maksym  staff   8039568 Jan  1  1970 apiregister-gen
-r-xr-xr-x@ 1 maksym  staff   6045088 Jan  1  1970 apiserver-boot
-r-xr-xr-x@ 1 maksym  staff   7326560 Jan  1  1970 client-gen
-r-xr-xr-x@ 1 maksym  staff   6911856 Jan  1  1970 conversion-gen
-r-xr-xr-x@ 1 maksym  staff   6913344 Jan  1  1970 deepcopy-gen
-r-xr-xr-x@ 1 maksym  staff   6885488 Jan  1  1970 defaulter-gen
-r-xr-xr-x@ 1 maksym  staff  10787248 Jan  1  1970 gen-apidocs
-r-xr-xr-x@ 1 maksym  staff   7062704 Jan  1  1970 informer-gen
-r-xr-xr-x@ 1 maksym  staff   6865680 Jan  1  1970 lister-gen
-r-xr-xr-x@ 1 maksym  staff  12830768 Jan  1  1970 openapi-gen
-r-xr-xr-x@ 1 maksym  staff  30132181 Jan  1  1970 vendor.tar.gz
 /usr/local/apiserver-builder/bin  apiserver-boot -h
2018/07/06 14:11:09 apiserver-boot must be run from the directory containing the go package to bootstrap. This must be under $GOPATH/src/<package>.
Current GOPATH=/Users/maksym/go.
Current directory=/usr/local/apiserver-builder/bin
```

**Comment by mlushpenko** [comment]
@damongant tried that, still the same

```
 ~/go  apiserver-boot -h
2018/07/07 12:00:43 apiserver-boot must be run from the directory containing the go package to bootstrap. This must be under $GOPATH/src/<package>.
Current GOPATH=/Users/maksym/go.
Current directory=/Users/maksym/go
 ✘  ~/go  cd src
 ~/go/src  apiserver-boot -h
2018/07/07 12:00:50 apiserver-boot must be run from the directory containing the go package to bootstrap. This must be under $GOPATH/src/<package>.
Current GOPATH=/Users/maksym/go.
Current directory=/Users/maksym/go/src
```

**Comment by damongant** [comment]
Why does your GOPATH have a trailing dot?

**Comment by mlushpenko** [comment]
It comes from an error message

```
~/go/src  echo $GOPATH
/Users/maksym/go
~/go/src  env | grep GOPATH
GOPATH=/Users/maksym/go
```

**Comment by mlushpenko** [comment]
Here is my go version, not sure if it is important

```
 ~/go/src  go version
go version go1.10.1 darwin/amd64
```

**Comment by damongant** [comment]
Looks like you _must_ be inside the `src` directory, and not the root of it.

**Comment by mlushpenko** [comment]
As you can see above, I tried inside src as well

![image](https://user-images.githubusercontent.com/2006610/42411239-fdb469ac-81f8-11e8-8e6d-0401e68f92a0.png)

Perhaps I must be in one of these?
```
 ~/go/src  ls
apiregister-gen   client-gen        deepcopy-gen      github.com        gopkg.in          lister-gen
apiserver-boot    cloud.google.com  defaulter-gen     golang.org        informer-gen      openapi-gen
bitbucket.org     conversion-gen    gen-apidocs       google.golang.org k8s.io
```

**Comment by damongant** [comment]
The `src` directory is the root of all packages, so if your package was named `github.com/mlushpenko/apiserver` it'd be in `$GOPATH/src/github.com/mlushpenko/apiserver`. Consequently, if your package was just in `$GOPATH/src` it's be named "", which doesn't work.

[Here's the Go docs with details](https://golang.org/doc/code.html)

**Comment by mlushpenko** [comment]
Thanks, @damongant this worked, after trying to find out to which package apiserver-builder belongs to:

```
~/go/src/github.com/kubernetes-incubator/apiserver-builder/pkg/apiserver  /usr/local/apiserver-builder/bin/apiserver-boot -h
```

But in general, between the lines so to say, my message was that installation manual is not good enough - if you just follow steps you end up with nothing because you can't use that binary, any ideas how to make it work out of the box?

**Comment by damongant** [comment]
Ah no, you misunderstood what it does - it generates a new package for you in your namespace.

All code in Go lives in the GOPATH, the link I posted previously should have all the details.

**Comment by AdelBouridah** [comment]
Hi @mlushpenko   I have the same issue to install api-server so how have you resolved it please

**Comment by mlushpenko** [comment]
I haven't :) I don't remember anymore what I was trying to test, but eventually I just dropped the idea.

**Comment by AdelBouridah** [comment]
thank you @mlushpenko  I have juste created the directory /go/src/github.com/kubernetes-incubator/apiserver-builder/pkg/apiserver as you have explained and by executing the apiserver-boot -h from it, it has worked. So its about go directories
