### ISSUE TITLE
limits option not works

### ISSUE THREAD

**Issue by jwierzbo-intel** [kubernetes-incubator/apiserver-builder-alpha#252]
`api/v1/namespaces/my_ns/my_resource?limit=1` returns all elements.
In the code (`pkg/client/clientset_generated/clientset/typed/aggregator/v1/my_resource.go`) I see that `meta_v1.ListOptions` object is passed in the`List` method, but it doesn't work..

**Comment by damongant** [comment]
What version of K8S do you target?

**Comment by jwierzbo** [comment]
Is the k8s v.1.10+ supported?
 I've just found this issue: https://github.com/kubernetes-incubator/apiserver-builder/issues/241

**Comment by damongant** [comment]
We run the aggregated apiserver on 1.10, but the tooling is 1.9. I just wanted to rule out that you're using an ancient version.

(do note this project is largely unmaintained now and you should be using kubebuilder for new stuff)

**Comment by jwierzbo** [comment]
@damongant kubebuilder base on CRD and controller - it is not the same as extension api-server where you have your own storage for your resources. Am I correct?

**Comment by damongant** [comment]
Both end up in etcd one way or another, you can just use a different one with apiserver.

However, after speaking to @pwittrock about the uncertain future of apiserver aggregation I'd still not recommend it

**Comment by jwierzbo** [comment]
That's the point:
I'm looking for solution where I can use separate datastore (etcd or another), which apiserver-builder fulfill and kubebuilder doesn't..

**Comment by damongant** [comment]
You can *technically* use a different data store, but it's not exactly a "pluggable" interface.

As far as I heard the apiservice type aggregation into the main apiserver may be deprecated or entirely removed soon. It does sort of look like a dirty hack where most people are better served with CRDs, so I'm not too surprised.

**Comment by jwierzbo** [comment]
I've created new api-server based on https://github.com/kubernetes/sample-apiserver
To enable Paging, following flag has to be enabled:
`Paging` in `k8s.io/apiserver/pkg/storage/storagebackend/config.go`

Probably same solution will be work for this project.

**Comment by yue9944882** [comment]
hey folks, fyi it's fixed by kubernetes via [#67861](https://github.com/kubernetes/kubernetes/pull/67861)

**Comment by MikeSpreitzer** [comment]
@yue9944882 : it looks like you did #338 to try to address this issue.  But in #338 notice that the APIListChunking feature gate is read before the command line flags are parsed, so the pagination feature is not effectively controlled by the command line.  It would be more appropriate to read the feature gate setting after the command line flags have been parsed.
