### ISSUE TITLE
API Server Flags for Aggregation Layer

### ISSUE THREAD

**Issue by ruigulala** [kubernetes-incubator/apiserver-builder-alpha#258]
According to https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/

This aggregator documentation says to use these flags, but I believe these flags require an authenticating proxy. The documentation doesn’t talk about an authenticating proxy. Can you help me understand if the authenticating proxy is required? Are all the flags required? If not, when are they required?

Particularly, I'm interested in the for the following flags:
--requestheader-extra-headers-prefix=X-Remote-Extra-
--requestheader-group-headers=X-Remote-Group
--requestheader-username-headers=X-Remote-User

**Comment by damongant** [comment]
The future of the Kubernetes aggregation layer is uncertain; prefer using CRDs where possible.

**Comment by AlainRoy** [comment]
The metrics server, as documented at https://kubernetes.io/docs/tasks/debug-application-cluster/core-metrics-pipeline/ uses the API aggregation and recommends these flags. To use the metrics server, CRDs are not currently possible, are they?

Towards that end, we'd love to understand these flags better, if you can help us understand them.

Thanks!

**Comment by yue9944882** [comment]
/triage support

https://kubernetes.io/docs/reference/access-authn-authz/authentication/#authenticating-proxy

these flags defines how the delegated authenticator extracts user informations from the requests, they are optional.
