### ISSUE TITLE
deepcopy-gen cannot recognize alias

### ISSUE THREAD

**Issue by magicsong** [kubernetes-incubator/apiserver-builder-alpha#279]
I have a type like:
```
type MyType string
```
And deepcopy-gen report following error：
```
deepcopy.go:866] Hit an unsupported type invalid type
```
So I have to remove the alias and use string directly. Does i miss something ?

**Comment by magicsong** [comment]
I found out `type MyType string` is missing in `zz_generated.api.register.go`, How do i tell apiregister-gen to copy this type

**Comment by magicsong** [comment]
@yue9944882 yes. I have the annotation. The root cause is `type MyType string` is missing in "zz_generated.api.register.go", when deepcopy try to generate deepcopy function of "zz_generated.api.register.go", it can't recognize `MyType`

**Comment by yue9944882** [comment]
@magicsong confirmed, thx!

/kind bug
/assign

**Comment by yue9944882** [comment]
@magicsong do you think about workaround like:

```go
type MyType struct {
    Value String
}
```

**Comment by magicsong** [comment]
@magicsong The usage of `type MyType string` is try to emulate "emum", (you know `golang` does not support emum). Your provided solution cannot achieve that aim.

**Comment by joeylin** [comment]
@magicsong  do you know how to fix this?

**Comment by joeylin** [comment]
@magicsong when i remove doc.go file，it  run well

**Comment by magicsong** [comment]
@joeylin I think remove `doc.go` is very dangerous. Because it has some annotations like following:
```
// +k8s:openapi-gen=true
// +k8s:deepcopy-gen=package,register
// +k8s:conversion-gen=github.com/magicsong/xxx//pkg/apis/devops
// +k8s:defaulter-gen=TypeMeta
// +groupName=xx.io
```
remove such annotations will make you api been unknow to apiserver.

**Comment by magicsong** [comment]
@joeylin right now  i put such types into another package instead of current versioned package. When i define my resources, i just import that package. This is a 100% workround and is not what is like in k8s source code.

**Comment by magicsong** [comment]
@yue9944882 it cannot work. should manually put `type MyType string` into the generated unversioned api

**Comment by brycecr** [comment]
I'm getting a similar error, but only on some environments...all the environments have the same go version. There are two packages in my pkg/ section, but only doc.go for one of them -- is that relevant? 

Two related questions:
> is there a way I can narrow down which type is calling this problem?
> is there a recommended way to clear my cache so I can verify that that cached generated files are not the issue? I can delete zz_generated.go and it gets recreated...

**Comment by filmil** [comment]
Added a somewhat nicer error message: https://github.com/kubernetes/gengo/pull/137

**Comment by vsxen** [comment]
you need run `go get -v -u k8s.io/apimachinery`
