### ISSUE TITLE
[Announcement] Repo renaming: Better builder tooling for AA is yet to come

### ISSUE THREAD

**Issue by yue9944882** [kubernetes-incubator/apiserver-builder-alpha#301]
As we discussed and decided, the repo is going to be renamed to `apiserver-builder-alpha` in the near future. Also the good news is some other builder toolings is landing for  __A__ PIServer __A__ ggregation developers (hopefully that will be landing next month Feb 2019), and that is going to be an awesome work by what we learned from previous practices that [building layered abstraction helps improve efficiency and quality of your work](https://www.youtube.com/watch?v=0tX3q_WAEdE&t=0s&list=PLj6h78yzYM2PZf9eA7bhWnIh_mK1vyOfU&index=264). 

As for this repo, it could be another fresh start after the renaming. We will aim to introducing some further integration w/ kubebuilder libraries which might be breaking backward-compatibilities such as replacing generated controller biolerplates to `controller-runtimes` in the future. In a word, a general goal is to reduce the duplication from existing builder suites under [k-sigs](https://github.com/kubernetes-sigs) and we can make best use of existing work and try to focus on attempting or even solving a better layered abstraction for AA.

Additionally, there's [a long discussion](https://docs.google.com/document/d/1y16jKL2hMjQO0trYBJJSczPAWj8vAgNFrdTZeCincmI/edit#)  over choices between CRD or AA which might be sort of a concern or confusion for developers trying to customize/extend kubernetes. Even though this topic doesn't seem to have final answer in short term but i believe our answer would be __you can pick both__ ideally. A layered, high-leveled abstraction would be helping you to get rid of such choices or even you could easily switch between either ways. While as far as we can see in the near future, AA would still be more capable  if you are willing to spend some time digging into upstream api-machinery libraries, or maybe things would be different when we finally graduate CRD to GA.

/cc @pwittrock  @kubernetes-incubator/maintainers-apiserver-builder

#### More FYI

- Since that renaming means relocating on Github,  all import paths in this repo are going to be __updated in a follow-up pull__. Unless you're really sure to upgrade your project before that the new tooling comes out, you are suggested to either switch the package path or stick on the old package path (github.com/kubernetes-incubator/apiserver-builder/...) in a fork. 
- Feel free to write down your thought if you got any. 🙂

**Comment by ChenDoRo** [comment]
Any schedule for controller-runtime library adoption? Or it is still in planning?

**Comment by ChenDoRo** [comment]
@yue9944882 Awesome!
