### ISSUE TITLE
[Feature] AA server should support logtostderr and log-dir flag as kubernetes apiserver

### ISSUE THREAD

**Issue by adohe** [kubernetes-incubator/apiserver-builder-alpha#306]
FYI. @yue9944882 @pwittrock ptal

**Comment by yue9944882** [comment]
putting this in detail, for now logs from AA server can only be printed at stdout/stderr. in order to land logs chunk gracefully in files, we need to migrate similar flags and their implementation from kube-apiserver. reusing work from k/logs is considered as a good step to start

**Comment by adohe** [comment]
sounds reasonable to me. 👍

**Comment by yue9944882** [comment]
Trying to switch the vendor dependency but hitting this very issue: [https://github.com/kubernetes/kubernetes/issues/74560](https://github.com/kubernetes/kubernetes/issues/74560)

**Comment by yue9944882** [comment]
Fixed by #309 

/close
