### ISSUE TITLE
How to add NewxxxREST for subresource

### ISSUE THREAD

**Issue by ckcd** [kubernetes-incubator/apiserver-builder-alpha#311]
Hi,  i am a beginner of this beautiful repo, and i have a question about `NewxxxREST` for subresource.

As i learned, For `resource`, when add `rest=xxxREST` in comment, the `apiserver-boot build generated` will do below as shown in [adding_custom_rest.md](https://github.com/kubernetes-incubator/apiserver-builder-alpha/blob/v1.9-alpha.4/docs/adding_custom_rest.md) ：

> You can implement your own REST implementation instead of using the standard storage by providing the rest=KindREST parameter and providing a newKindREST() rest.Storage {} function to return the storage.

which means we can define any variable in `type xxxREST struct` and define a `NewxxxREST` which will be reference in `zz_generated.api.register.go`, for example, in my code, i set a `genericregistry.Store` in `FooREST` rather than `registry`, and it works well :

```
type FooREST struct {
	*genericregistry.Store
}

// Initialize custom REST storage
func NewOneTimeURLREST() rest.Storage {
	genericStore := &genericregistry.Store{
		...
	}

	options := &generic.StoreOptions{RESTOptions: RESTOptionsGetter, AttrFunc: GetAttrs}
	if err := genericStore.CompleteWithOptions(options); err != nil {
		panic(err)
	}

	fooREST := &OneTimeURLREST{genericStore}
	return fooREST
}

func (o *FooREST) Get(ctx request.Context, name string, options *metav1.GetOptions) (runtime.Object, error) {
	return o.Store.Get(ctx, name, options)
}
...
```

However, when add `subresource`, i met a problem because there is NO `NewxxxREST` for `subresource` in `zz_generated.api.register.go`, instead it just strictly set as:

```
func() rest.Storage {
	return &SubFooREST{net.NewFooRegistry(netFooStorage)}
}
```

which means `subresource` must use `registry` and can not use my self-defined store(e.g.  generic.Store).

this causes dangerous problem for me: when i do `Sub()` using `clisntset_generated`, i got an error:
```
runtime error: invalid memory address or nil pointer dereference
.../pkg/apis/net/zz_generated.api.register.go:242
.../pkg/apis/net/v1alpha1/sub_foo_types.go:74
.../vendor/k8s.io/apiserver/pkg/endpoints/handlers/update.go:101
.../vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:182
```

which means the `st` in next code is `nil`:
```
func (s *storageFoo) GetFoo(ctx request.Context, id string, options *metav1.GetOptions) (*Foo, error) {
	st := s.GetStandardStorage()
	obj, err := st.Get(ctx, id, options)
	if err != nil {
		return nil, err
	}
	return obj.(*Foo), nil
}
```

and i read code of `kubbernetes-incubator/apiserver-builder/kg/builders/api_versioned_resouce_builder.go`, i find `b.GetStandardStorage()` returns `b.Storage` which is used in `GetFoo`, but it seems no one will update the `b.Storage` if we use `xxxREST` so it's `nil` always.

So i was wandering of whether we can add `NewxxxREST` for subresource ? so i can use any `store` for `subresource`.

Or is there any methods to link my `Store` with `registry` ?

And if i have some wrong operation please correct me !

thanks !!!

**Comment by yue9944882** [comment]
thx for reporting this!

> it seems no one will update the `b.Storage` if we use `xxxREST` so it's `nil` always

this sounds surprising. could u expand it in detail how are we hitting the nil panic? if i understand correctly `b.GetStandardStorage()` seems never returning a nil instance.

> so i can use any `store` for `subresource`.

what's the purpose of replacing the store? as a rule of thumb, it's designed that the main resource and its subresources sharing the store.

**Comment by ckcd** [comment]
@yue9944882  Thanks for your opionion !  and sorry to reply you so later.

> if i understand correctly b.GetStandardStorage() seems never returning a nil instance.

Yes, `b.GetStandardStorage()` returns `b.Storage` but  no one can initialize `b.Storage` if we use `REST` rather than `Strategy`, in my rough opinion, the flow of execution is:

1. if set `strategy=FooStrategy`, then: `builders.NewApiResource()`  --> `registerEndpoints()` --> `registry[path] = b.Build(group, optionsGetter)` --> `Build()`  --> `b.Storage = store`, which means the `Build()` func will update `b.Storage` from `nil` to something.

2. if set `REST=FooREST`, then: `builders.NewApiResourceWithStorage()` --> `registerEndpoints()` --> `registry[path] = b.RESTFunc()`, and i cannot see some one can update `b.Storage`;

3. the CRUD apis (e.g. `ListFoos()`) always use `b.GetStandardStorage()` rather than `b.RESTFunc()`, so i get `nil` when use `REST`.

> what's the purpose of replacing the store? as a rule of thumb, it's designed that the main resource and its subresources sharing the store.

if i want to set different store param (e.g. `Decorator`) for resource and subresource, i must operate each `store` respectively. For now to workaround, when operator subresource(such as `(r *subREST) Create()`), i have to do this:

```
// 1. trans global storage to storageWrapper
storageWrapper, ok := xxxFooStorage.Storage.(*builders.StorageWrapper)

// 2. Deep copy a new store
localStorageWrapper := *storageWrapper

// 3. make different params for new store
localStorageWrapper.Decorator = nil
```

**Comment by yue9944882** [comment]
thx for the detailed clarification! i did reproduce that in my local environment. will file a pull for allowing injecting store when customizing REST 🔨
