### ISSUE TITLE
v1.12.alpha.2 linux-amd build appears to be for another architecture (darwin-amd?)

### ISSUE THREAD

**Issue by admilazz** [kubernetes-incubator/apiserver-builder-alpha#323]
This might be a duplicate of #153, but it seems that the apiserver-boot binary (and probably others) in v1.12.2-linux-amd64 are not ELF images and fail with the error "apiserver-boot: cannot execute binary file: Exec format error".

**Comment by yue9944882** [comment]
sry for the negligence, it was a misconfiguration in our CI environment. binaries updated.

/close
