### ISSUE TITLE
Missing manifest.json when try to generate swagger.json

### ISSUE THREAD

**Issue by tony-shi** [kubernetes-incubator/apiserver-builder-alpha#348]
I was try to use apiserver-builder to generate a swagger.json esaily with several bash command.
Things works pretty well until in the last step
```bash
apiserver-boot build docs --cleanup=false
```
I want to keep the clean up as false, to see the intermediate resources, including the swagger.json i needed.
In fact i got a swagger.json in the docs/openapi-spec directory since i add the --cleanup=false flag.
However the terminal always output likes below
```bash
2019/05/09 20:15:15 docker run -v /Users/shihuashen/go/src/shihuashen/test/docs/includes:/source -v /Users/shihuashen/go/src/shihuashen/test/docs/build:/build -v /Users/shihuashen/go/src/shihuashen/test/docs/build:/build -v /Users/shihuashen/go/src/shihuashen/test/docs:/manifest pwittrock/brodocs
cp: cannot stat '/manifest/manifest.json': No such file or directory
module.js:472
    throw err;
    ^

Error: Cannot find module './manifest'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/brodocs/brodoc.js:24:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
I think this is because the lack of manifest.json which need by the brodoc. 
The apiserver-boot version shows like below:
```json
Version: version.Version{ApiserverBuilderVersion:"v1.12.alpha.2", KubernetesVendor:"1.12.3", GitCommit:"3554ff8abc71d3e29c2feba82b1f1126ddb4c0aa", BuildDate:"2019-03-12-18:55:58", GoOs:"darwin", GoArch:"amd64"}
```
Any suggestions?

**Comment by yue9944882** [comment]
thank you for reporting this. it's a bug left by over-trimming the vendor in recent change. will fix it at the release in mid may.

for now, as a walkaround, you can generate the openapi docs by running apiserver manually using the flag `--print-openapi`. (additionally, launching apiserver requires `--etcd-servers` flag).

/assign
