### ISSUE TITLE
customize etcd servers

### ISSUE THREAD

**Issue by wellorange** [kubernetes-incubator/apiserver-builder-alpha#360]
Why can't I customize etcd?I already have a etcd on my machine.
```
apiserver-boot run  local --etcd=http://127.0.0.1:2379
```
```
enerated --listers-package demo/pkg/client/listers_generated --versioned-clientset-package demo/pkg/client/clientset_generated/clientset
2019/06/10 10:40:10 CGO_ENABLED=0
go build -o bin/apiserver cmd/apiserver/main.go
go build -o bin/controller-manager cmd/manager/main.go
etcd
2019/06/10 10:40:17 Failed to run etcd exit status 1
```

**Comment by yue9944882** [comment]
it seems that the command is failing b/c there's no `etcd` binaries installed in your `$PATH`. and sadly for now, run local only works for local etcd cluster.

**Comment by wellorange** [comment]
@yue9944882 Because I have the etcd service locally, I don't need to start a new etcd instance. etcd has fixed port 2379. I can't start the new etcd service on this machine.

**Comment by wellorange** [comment]
@yue9944882 My etcd service has another use, can't be closed, because etcd fixed port reason, I can't start new service again.

**Comment by yue9944882** [comment]
oh i see, if thats the case, you can exclude etcd bootstrapping via `apiserver-boot run local --run apiserver --run controller-manager`.

**Comment by wypsmall** [comment]
apiserver-boot run local-minikube --etcd=http://127.0.0.1:3379 --run="apiserver,controller-manager"

**Comment by yue9944882** [comment]
/close

closing as the question seems resolved.
