### ISSUE TITLE
[Bug] api-conventions.md does not exit

### ISSUE THREAD

**Issue by shuijing198799** [kubernetes-incubator/apiserver-builder-alpha#383]
In the page : https://github.com/kubernetes-incubator/apiserver-builder-alpha/blob/master/docs/concepts/api_building_overview.md
The link https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md can't be found anymore

**Comment by yue9944882** [comment]
thank you for reporting this. will fix the broken link, the active one is here:

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md
